server:
  port: 7001

spring:
#region: db
  data:
    mongodb:
      database: skiclub
      host: localhost
      port: 27017
#endregion
#region: trace
  zipkin:
    base-url: http://localhost:9411/
    service:
      name: equipment-api
#endregion

logging:
  level:
    org.springframework: INFO