server:
  port: 6003

spring:
  #region: trace
  zipkin:
    base-url: http://localhost:9411/
    service:
      name: ${spring.application.name}
  #endregion
  #region: kafka
  kafka:
    default-topic: ski-orders
    admin:
      fail-fast: true
    bootstrap-servers: http://localhost:29092
    consumer:
      client-id: ${spring.application.name}
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: http://localhost:29092
      auto-offset-reset: latest
#endregion
