server:
  port: 7002

integration:
  web:
    url: 'http://localhost:9095'

spring:
#region: db
  data:
    mongodb:
      database: skiclub
      host: localhost
      port: 27017
#endregion
#region: trace
  zipkin:
    base-url: http://localhost:9411/
    service:
      name: order-api
#endregion
#region: kafka
  kafka:
    admin:
      fail-fast: true
    bootstrap-servers:
      – http://localhost:29092
      – http://localhost:39092
    producer:
      client-id: order-api
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 50
      bootstrap-servers:
        – http://localhost:29092
        – http://localhost:39092
    template:
      default-topic: ski-orders
#endregion
